### ISSUE TITLE
为啥我的nav生成的是xxx.html呢？

### ISSUE THREAD

**Issue by 623636245** [boboidream/note#7]
![image](https://user-images.githubusercontent.com/22848900/96227898-5f7f0300-0fc7-11eb-9235-a525d0487eab.png)
配置文件和你一样的

**Comment by 623636245** [comment]
![image](https://user-images.githubusercontent.com/22848900/96228375-17acab80-0fc8-11eb-829e-4cdfa6cce175.png)
![image](https://user-images.githubusercontent.com/22848900/96228430-2d21d580-0fc8-11eb-8098-0afedc7a53b0.png)
![image](https://user-images.githubusercontent.com/22848900/96228441-314df300-0fc8-11eb-9c0b-0c67557335ec.png)
搞了好久都没对

**Comment by boboidream** [comment]
是你自己 navConf 里填的？而且这 plugins 插件配置写法是新写法？

我的是这么写的
`plugins: ['permalink-pinyin', ['autobar', {'pinyinNav': true}], 'rpurl'],`

要不你直接把我的 Note 项目里 docs 内容删了，改成你的好了。如果方便的话放个 repo 地址，看看也行

**Comment by 623636245** [comment]
奇了怪了。我把你的搞下來也是欸
![image](https://user-images.githubusercontent.com/22848900/96390673-53be5700-11e8-11eb-8947-549194e32d37.png)

**Comment by boboidream** [comment]
这么神奇么。。。我的 note  是 travis 自动化编译，也没出问题啊。升级下 node 版本试试？

**Comment by 623636245** [comment]
![image](https://user-images.githubusercontent.com/22848900/96683220-6da89700-13ac-11eb-8c8b-c2c2fbb45bff.png)

源码里面改动了下 就好了

**Comment by boboidream** [comment]
这句，看起来不是把  `\` 符号替换为 `/`。好吧。。。解决就好
